---
type: service_template
subtype: container
name: ffmpeg-build-step
description: This is the base template for building  component.
container:
  resources:
    mem_mib: 1024
    cpu_cores: 0.3
    disk_gb: 10
  image: get.applatix.io/francis/ubuntu-build:16.10
  docker_options:
  command: sh -c 'docker login -u axuser -p VR/fZvoC0nA0 get.applatix.io 
    && /src/build.sh'
inputs:
  artifacts:
  - from: "%%service.checkout.code%%"
    path: "/src"
  parameters:
    checkout:
    namespace:
    version:
outputs:
labels:
    "ax_ea_docker_enable": "{ \"graph-storage-name\": \"platformbuildstorage\", \"graph-storage-size\": \"30Gi\" }"

---
type: service_template
subtype: workflow
name: ffmpge-build-standalone
description: This is the workflow for building components.
inputs:
  parameters:
    commit:
      default: "%%session.commit%%"
    repo:
      default: "%%session.repo%%"
    namespace:
      default: axsys
    version:
      default: staging
steps:
  - checkout:
      template: axcheckout
  - platform-build:
      template: ffmpeg-build-step
      parameters:
        checkout: "%%step.checkout%%"
